# Generated by Django 4.1.6 on 2023-10-24 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jop', '0002_alter_jop_experince_alter_jop_salary_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jop',
            old_name='cratesd_at',
            new_name='crated_at',
        ),
    ]
