# Generated by Django 4.1.6 on 2023-10-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jop', '0003_rename_cratesd_at_jop_crated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jop',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
