# Generated by Django 4.2.6 on 2023-10-31 14:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jop', '0004_jop_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jop',
            options={'ordering': ['-id']},
        ),
        migrations.CreateModel(
            name='JopForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('link_url', models.URLField(blank=True, help_text='please enter your linked in account', null=True)),
                ('github_url', models.URLField(help_text='please enter your github account')),
                ('cv', models.FileField(help_text='please uplouad your CV', upload_to='cv')),
                ('cover_letter', models.TextField(max_length=600)),
                ('crated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('Jop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_form', to='jop.jop')),
            ],
        ),
    ]
