# Generated by Django 4.2.6 on 2023-11-02 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jop', '0007_alter_jopform_github_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jopform',
            name='Jop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_form', to='jop.jop'),
        ),
    ]
