# Generated by Django 4.2.6 on 2024-01-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('phone_num', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=300)),
            ],
        ),
    ]
