# Generated by Django 4.2.6 on 2024-01-08 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auther'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='auther',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='auther_blog', to='blog.auther'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='auther_comment',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
