# Generated by Django 4.2.6 on 2024-01-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_auther_blog_auther_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='auther_comment',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='qoute',
            field=models.TextField(max_length=1000),
        ),
    ]
